	<style>   
    /* embedded  CSS */
		@media screen and (max-width: 767px){    
		#logo-text 
		{  
		display: none;
		}  

		#display-footer{ 
		display: none;
		} 

		}
		div#images{   

		display: flex;

		flex-direction: column; 
		float: right; 
		justify-content: space-around;	 
		margin: 10px;

		}  
    /* Main CSS */    
		main{ 
		background-color: #fff;  
       margin-top: 65px;
       
		}
    /* Body Images CSS */
		#Content-image{ 
		float: right;  

		border: 1px solid #ddd;
		border-radius: 4px;
		padding: 5px; 
		transition: transform .2s;

		}  
		#Content-image:hover {
		-ms-transform: scale(1.5); 
		-webkit-transform: scale(1.5); 
		 transform: scale(1.5); 
		}
		#Content-image-two{   
		float: right;  
		border: 1px solid #ddd;
		border-radius: 4px;
		padding: 5px; 
		transition: transform .2s;
		}   
		#Content-image-two:hover {
		-ms-transform: scale(1.5); 
		-webkit-transform: scale(1.5); 
		transform: scale(1.5); 
		} 

		@media screen and (min-width: 767px){  
		#mob-nav{ 
		display: none;
		} 
	    }  
        button#login, button#login1{
        background-color: #666;
        border: none;
        } 
        /* CSS for navigation*/
      

	</style>