<style> 
	  @media screen and (max-width: 767px){   
	  #main-image{ 
	  width: 100%;
	  }  
      #logo-text 
      {  
      display: none;
      }  
      div.gallery {  
      width: 100%;  
      
      } 
      #display-footer{ 
      display: none;
      } 

	  main{
      min-height: 3000px; 
	  padding: 60px;
      }  
	   
	  #grad1 {   
      position: absolute; 
      top: 11.5%;
	  }
	  #main-image{ 
	  margin-top: 44px
	  }
	  } 
      @media screen and (min-width: 768px){ 
      main{ 
      min-height: 1100px;
      }  
      div.gallery {  
      width: 180px; 
      } 
      #grad1 {   

      position: absolute; 
      top: 22%;

      } 
      main{
      min-height: 1400px;  
      background-color: #fff;
	  padding: 30px;
      }
      } 
      div.gallery {
      margin: 5px;
      border: 1px solid #ccc;
      float: left;
      
      margin: 30px; 
      height: 300px;
      }

      div.gallery:hover {
      border: 1px solid #777; 
      padding: 30px;
      }

      div.gallery img {
      width: 100%;
      height: auto; 

      }

      div.desc {
      padding: 10px;
      text-align: center;
      } 
      #socialmedia{ 
      position: absolute; 
      top: 50% ;
      right: 100%;
      } 
      button{
      background-color: #f00;
      color: white;
     
      height: auto;
      border: none;
      cursor: pointer; 
     
      width: auto;
     
      background-color: #f44336;

      }  
       button#login, button#login1{
      background-color: #666;
     
      }
      div#music div.desc{  

      margin-bottom: 40px;
      } 

       
      
</style>