<style > 
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
#prof {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#prof td, #prof th {
  border: 1px solid #ddd;
  padding: 8px;
}

#prof tr:nth-child(even){background-color: #f2f2f2;}

#prof tr:hover {background-color: #ddd;}

#prof th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #000;
  color: white;
}


          
.sidenav { 
     height: 500px;
    width: 200px;
    position: absolute;
    z-index: 1;
    top: 690px;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main { 
  margin-left: 180px; /* Same as the width of the sidenav */
  /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
table {
            border-collapse: collapse;
            width: 100%;
        }

        th {
            text-align: left;
            padding: 6px;
        }
        td {
            border: 1px solid #cfcfcf;
            padding: 6px;
        }

        #cart {
            display: inline-block;
            position: absolute;
            top:0px;
            right: 0px;
            color: #FFF;
            background: #000;
            font-size: 1px;
            padding: 10px;
        }
        .container {
             
            height: 700px;
            padding-top: 100px;
            position: relative;
        }

        #cart a:link, #cart a:visited {
            color: #fff;
            font-size: 1px;
        }
        #cart a:hover, #cart a:active {
            color: #fff;
            font-size: 1px;
        } 
</style>