<style>  

#prof {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#prof td, #prof th {
  border: 1px solid #ddd;
  padding: 8px;
}

#prof tr:nth-child(even){background-color: #f2f2f2;}

#prof tr:hover {background-color: #ddd;}

#prof th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #000;
  color: white;
}


          
.sidenav { 
    height: 500px;
    width: 180px;
    position: absolute;
    z-index: 1;
    top: 690px;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main { 
  margin-left: 180px; /* Same as the width of the sidenav */
  /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
} 
main{ 
padding: 0;  
background-color: #fff;
 }
      
</style>