<style> 
	  @media screen and (max-width: 767px){   
	  #main-image{ 
	  width: 100%;
	  }  
      #logo-text 
      {  
      display: none;
      }  
      div.gallery {  
      width: 100%;  
      
      } 
      #display-footer{ 
      display: none;
      } 

	  main{
      min-height: 3000px; 
	  padding: 60px;
      }  
	   
	
	  #main-image{ 
	  margin-top: 44px
	  }
	  } 
      @media screen and (min-width: 768px){ 
      main{ 
      min-height: 1100px;
      }  
      div.gallery {  
      width: 180px; 
      } 
      
      main{
      min-height: 1400px;  
      background-color: #fff;
	  padding: 30px;
      }
      } 
      div.gallery {
      margin: 5px;
      border: 1px solid #ccc;
      float: left;
      
      margin: 30px; 
      height: 300px;
      }

      div.gallery:hover {
      border: 1px solid #777; 
      padding: 30px;
      }

      div.gallery img {
      width: 100%;
      height: auto; 

      }

      div.desc {
      padding: 10px;
      text-align: center;
      } 
      #socialmedia{ 
      position: absolute; 
      top: 50% ;
      right: 100%;
      } 
      button{
      background-color: #f00;
      color: white;
     
      height: auto;
      border: none;
      cursor: pointer; 
     
      width: auto;
     
      background-color: #f44336;

      }  
       button#login, button#login1{
      background-color: #666;
     
      }
      div#music div.desc{  

      margin-bottom: 40px;
      } 

      body {font-family: Arial, Helvetica, sans-serif;}
      * {box-sizing: border-box;}

      input[type=text], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
      }

      input[type=submit] {
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
      }

      input[type=submit]:hover {
        background-color: #45a049;
      }

      .container {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
      }  
      span.error{

			color: #900;
		}
      
</style>