	<style>  
    
	  @media screen and (max-width: 767px){   
	  #main-image{ 
	  width: 100%;
	  }  
      #logo-text 
      {  
      display: none;
      } 
      #display-footer{ 
      display: none;
      } 

	  main{
      min-height: 2200px; 
	  padding: 60px;
      }  
	   
	  #grad1 {   
      position: absolute; 
      top: 11.5%;
	  }
	  #main-image{ 
	  margin-top: 44px
	  }
	  } 
      @media screen and (min-width: 768px){ 
      main{ 
      min-height: 1100px;
      } 
      #grad1 {   

      position: absolute; 
      top: 16.4%;

      }
      } 
       div.gallery {
      margin: 5px;
      border: 1px solid #ccc;
      float: left;
       
      margin: 30px; 
      
      }

      div.gallery:hover {
      border: 1px solid #777; 
      padding: 30px;
      }

      div.gallery img {
      width: 100%;
      height: auto; 

      }

      div.desc {
      padding: 10px;
      text-align: center;
      } 
      #socialmedia{ 
      position: absolute; 
      top: 15% ;
      right: 100%;
      } 
      button{
      background-color: #f00;
      color: white;
      
      margin-top: 10px;
      border: none;
      cursor: pointer; 
      

      }  
       button#login, button#login1{
      background-color: #666;
     
      }
      div#music div.desc{  

      margin-bottom: 40px;
      } 

      main{   
      background-color: #fff;
      padding: 30px;
      
      } 
      table{
           
       border: 2px solid #000;
        border-spacing: 0px;
        border-collapse: collapse;
        width: 700px; 
        
      }
      
      /*Cells style sheet  with border and padding theme */
      
      td,th{ 
        border: 1px solid #666;
        padding: 0px;
      } 
       /*Header cells style sheet using background and text colour  */
      th{ 
        background-color: #bbf;
        color: #000;
        
      }
          
      th code{   
        
        font-weight: 700;
      
      }
      /* With CSS, the <caption> tag with theme of grey background and black text
      better than before. */ 
      table caption{ 
      
        background-color: #bbf;
        color:#000;
      } 
</style>